config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "calendar#index"
  resources :users, only: [:edit, :update]

  resources :calendar_rooms, only: [:index, :new, :create] do
    resources :calendars, only: [:index, :create]
  end

  resources :chat_rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_type.rb
class BloodType < ActiveHash::Base
  self.data = [
    { id: 1, name: '血液型を選択してください' },
    { id: 2, name: 'A型' },
    { id: 3, name: 'B型' },
    { id: 4, name: 'O型' },
    { id: 5, name: 'AB型' },
    { id: 6, name: '分からない' },
  ]
  
  include ActiveHash::Associations
  has_many :calendar_room

end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :calendar_room
  belongs_to :user

  validates :detail, presence: true
end

app/models/calendar_room.rb
class CalendarRoom < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :sex
  belongs_to_active_hash :blood_type

  belongs_to :user
  belongs_to :calendar

  with_options presence: true do
    validates :child_name
    validates :birth_date
    validates :sex_id,        numericality: { other_than: 1 }
    validates :blood_type_id, numericality: { other_than: 1 }
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages

  validates :name, presence: true

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :content, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 1, name: '性別を選択してください' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' },
    { id: 4, name: 'ヒミツ' },
  ]

  include ActiveHash::Associations
  has_many :calendar_room

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates_format_of :email, { with: EMAIL_REGEX, uniqueness: { case_sensitive: false } }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d{6,}]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  validates :name, presence: true

  has_many :calendar_rooms
  # has_many :events
  has_many :room_users
  has_many :chat_rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @calendar = Calendar.new
    # @calendar_room = CalendarRoom.find(params[:calendar_room_id])
    # @calendars = @calendar_room.calendars.includes(:user)
  end

  def create
    @calendar_room = CalendarRoom.find(params[:calendar_room_id])
    @calendar = @calendar_room.calendar.new(calendar_params)
    if @calendar.save
      redirect_to root_path
    else
      # @calendars = @calendar_room.calendars.includes(:user)
      render :index
    end
  end

  private

  def calendar_params
    params.require(:calendar).permit(:detail).merge(user_id: current_user.id)
  end
end

app/controllers/calendar_rooms_controller.rb
class CalendarRoomsController < ApplicationController

  def index
    @calendar_rooms = CalendarRoom.calendar("created_at DESC")
  end

  def new
    @calendar_room = CalendarRoom.new
  end

  def create
    binding.pry
    @calendar_room = CalendarRoom.new(calendar_room_params)
    if @calendar_room.save
      redirect_to root_path
    else
      return render :new
    end
  end

  private

  def calendar_room_params
    params.require(:calendar_room).permit(:child_name, :birth_date, :sex_id, :blood_type_id).merge(user_id: current_user.id)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    if @chat_room.save
      redirect_to root_path
    else
      render :new
    end
  end
    
  private

  def chat_room_params
    params.require(:chat_room).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    # binding.pry
    @message = Message.new
    @chat_room = ChatRoom.new
    if @chat_room_id == nil
      redirect_to chat_rooms_path
    else
      @chat_room = ChatRoom.find(params[:chat_room_id])
    end
    @messages = @chat_room.messages.includes(:user)
  end

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message = @chat_room.messages.new(message_params)
    if @message.save
      redirect_to chat_room_messages_path(@chat_room)
    else
      @messages = @chat_room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/parents_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/calendar_rooms_helper.rb
module CalendarRoomsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/calendar/_main.html.erb
<div class="calendar-header"> <%#chat-header%>
  <div class="left-header">
    <div class="calendar-header-name">
      <%= link_to edit_user_path(current_user) do %>
        <%= current_user.name %>
      <% end %>
      <%#= @calendar_room.child_name %> さんのカレンダー
    </div>
  </div>
  
  <div class="calendar-right-header">
    <div class="calendar-header-button">
      <%= link_to "チャットルーム", chat_room_messages_path(chat_rooms_url) %>
    </div>
    <div class="calendar-header-button">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
    </div>
  </div>
</div>

<div class="calendar">
  <div id="calendar"></div>
  <script src="../../_common/scripts/jquery-3.4.1.min.js"></script>
  <%#= render partial: 'calendar', collection: @calendars %>
</div>

app/views/calendar/_side.html.erb
<div class="side-header"> <%#side-bar-header%>
  <div class="header-title">
    Child Calendar
  </div>
</div>


<div class="children">
  <% current_user.calendar_rooms.each do |calendar| %>
    <div class="child">
      <div class="child-name">
        <%#= link_to calendar_room.child_name, root_path(current_user) %> さん
      </div>
    </div>
  <% end %>
</div>

<div class="side-footer">
    <div class="create-calendar">
      <%= link_to "カレンダーを作成する", new_calendar_room_path %>
    </div>
</div>

app/views/calendar/index.html.erb
<div class="wrapper">
  <div class="side">
    <%= render "side" %>
  </div>
  <div class="main">
    <%= render "main" %>
  </div>
</div>

app/views/calendar_rooms/index.html.erb
<div class='wrapper'>
  <div class='side'>
    <%= render "calendars/side" %>
  </div>
</div>

app/views/calendar_rooms/new.html.erb
<div class='calendar-room-form'>
  <h1>新規カレンダー</h1>
  <%=form_with model: @calendar_room, local: true do |f|%>
    <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'>
        <%= f.label :お子さんのお名前, class: 'calendar-room-form__label'%>
      </div>
      <div class='calendar-room-form__field--right'>
        <%= f.text_field :child_name, class: 'calendar__room_name calendar-room-form__input', placeholder: 'お子さんのお名前を入力してください'%>
      </div>
    </div>
    <div class='calendar-room-form__field'>
    </div>
    
    <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'>
        <%= f.label :誕生日, class: 'calendar-room-form__label'%>
      </div>
      <div class='calendar-room-form__field--right'>
        <%= f.text_field :birth_date, class: 'calendar__room_name calendar-room-form__input', placeholder: '2000/01/01'%>
      </div>
    </div>
    <div class='calendar-room-form__field'>
    </div>

    <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'>
        <%= f.label :性別, class: 'calendar-room-form__label'%>
      </div>
      <div class='calendar-room-form__field--right'>
        <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class: 'calendar__room_name calendar-room-form__input', placeholder: '性別を入力してください'})%>
      </div>
    </div>
    <div class='calendar-room-form__field'>
    </div>

    <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'>
        <%= f.label :血液型, class: 'calendar-room-form__label'%>
      </div>
      <div class='calendar-room-form__field--right'>
        <%= f.collection_select(:blood_type_id, BloodType.all, :id, :name, {}, {class: 'calendar__room_name calendar-room-form__input', placeholder: '血液型を入力してください'})%>
      </div>
    </div>
    <div class='calendar-room-form__field'>
    </div>

    <%# <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'>
        <label class='calendar-room-form__label' for='calendar_room_カレンダー'>カレンダー</label>
      </div>
      <div class='calendar-room-form__field--right'>
        <select name="calendar_room[user_ids][]">
          <option value="">カレンダーを選択してください</option> %>
          <%# User.where.not(id: current_user.id).each do |user| %>
            <%# <option value= %>
            <%#= user.id %>><%#= user.name %>
            <%# </option> %>
          <%# end %>
        <%# </select>  %>
        <%# <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>> %>
      <%# </div> %>
    <%# </div> %>
    <div class='calendar-room-form__field'>
      <div class='calendar-room-form__field--left'></div>
      <div class='calendar-room-form__field--right'>
        <%= f.submit class: 'calendar-room-form__action-btn'%>
        <%= link_to "マイページに戻る", :back, class: 'calendar-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/chat_rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/chat_rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @chat_room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="chat_room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="chat_room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
        <%= link_to "戻る", :back, class: 'calendar-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <% if  %>
    <div class="left-header">
      <div class="chat-header-name">
        <%= @chat_room.name %>
      </div>
    </div>

    <div class="calendar-right-header">
      <div class="calendar-header-button">
        <%= link_to "カレンダールーム", root_path %>
      </div>
      <div class="calendar-header-button">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      </div>
    </div>
  <% end %>

  <div class="chat-right-header">
    <div class="chat-header-button">
      <%= link_to "チャットを終了する", room_path(@chat_room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@chat_room, @message], html: {class: "form"}, local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
    <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
    <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
    <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize:'500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-title">
    Child Calendar
  </div>
</div>

<div class="rooms">
  <% current_user.chat_rooms.each do |chat| %>
    <div class="room">
      <div class="room-name">
        <%= link_to chat_room.name, chat_room_messages_path(chat_room) %>
      </div>
    </div>
  <% end %>
</div>

<div class="side-bar-footer">
  <div class="create-room">
    <%= link_to "チャットを作成する", new_chat_room_path %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "マイページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>